[remote.github]
owner = "cuervolu"
repo  = "piola"

[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
"""

body = """
{% if version %}\
    ## [{{ version | trim_start_matches(pat="v") }}]\
    {% if previous.version %} - {{ timestamp | date(format="%Y-%m-%d") }}{% endif %}

{% else %}\
    ## [Unreleased]

{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim | upper_first }}
{% for commit in commits %}\
    - {{ commit.message | upper_first }}\
    {% if commit.github.username %} by @{{ commit.github.username }}{% endif %}
{% endfor %}
{% endfor %}\n
"""

footer = """
{% for release in releases %}\
    {% if release.version %}\
        {% if release.previous.version %}\
            [{{ release.version | trim_start_matches(pat="v") }}]: \
                https://github.com/cuervolu/piola/compare/{{ release.previous.version }}..{{ release.version }}
        {% endif %}\
    {% else %}\
        [unreleased]: https://github.com/cuervolu/piola/compare/\
            {% if releases | length > 1 %}\
                {{ releases | nth(n=1) | get(key="version") }}\
            {% endif %}..HEAD
    {% endif %}\
{% endfor %}
<!-- generated by git-cliff -->
"""

trim         = true
render_always = true

[git]
conventional_commits    = true
filter_unconventional   = true
require_conventional    = false
split_commits           = false
protect_breaking_commits = false
filter_commits          = false
topo_order              = false
topo_order_commits      = true
sort_commits            = "oldest"

commit_parsers = [
    # Keep a Changelog: Added
    { message = "^feat",                   group = "Added"       },

    # Keep a Changelog: Changed
    { message = "^refactor",               group = "Changed"     },
    { message = "^perf",                   group = "Changed"     },
    { message = "^style",                  group = "Changed"     },

    # Keep a Changelog: Fixed
    { message = "^fix",                    group = "Fixed"       },

    # Keep a Changelog: Security
    { body    = ".*security",              group = "Security"    },
    { message = "^security",               group = "Security"    },

    # Keep a Changelog: Deprecated
    { message = "^deprecat",              group = "Deprecated"  },

    # Keep a Changelog: Removed
    { message = "^remove|^revert",         group = "Removed"     },

    { message = "^chore\\(release\\)",     skip  = true          },
    { message = "^chore\\(deps",           skip  = true          },
    { message = "^chore\\(pr\\)",          skip  = true          },
    { message = "^chore\\(pull\\)",        skip  = true          },
    { message = "^Merge",                  skip  = true          },
    { message = "^wip",                    skip  = true          },

    { message = "^doc",                    group = "Miscellaneous" },
    { message = "^test",                   group = "Miscellaneous" },
    { message = "^chore|^ci|^build",       group = "Miscellaneous" },
]