[remote.github]
owner = "cuervolu"
repo = "wn"

[changelog]
header = """
# Changelog

Acá están todos los cambios importantes del proyecto, mi chanchito.

El formato está basado en [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
y este proyecto sigue [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
"""

body = """
{% if version %}\
    ## [{{ version | trim_start_matches(pat="v") }}]\
    {% if previous.version %} - {{ timestamp | date(format="%Y-%m-%d") }}{% endif %}

{% else %}\
    ## [No publicado]

{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim | upper_first }}
{% for commit in commits %}\
    - {{ commit.message | upper_first }}\
    {% if commit.github.username %} por @{{ commit.github.username }}{% endif %}\
    {% if commit.github.pr_number %} ([#{{ commit.github.pr_number }}](https://github.com/cuervolu/wn/pull/{{ commit.github.pr_number }})){% endif %}
{% endfor %}
{% endfor %}\n
"""

footer = """
{% for release in releases %}\
    {% if release.version %}\
        {% if release.previous.version %}\
            [{{ release.version | trim_start_matches(pat="v") }}]: \
                https://github.com/cuervolu/wn/compare/{{ release.previous.version }}..{{ release.version }}
        {% endif %}\
    {% else %}\
        [unreleased]: https://github.com/cuervolu/wn/compare/\
            {% if releases | length > 1 %}\
                {{ releases | nth(n=1) | get(key="version") }}\
            {% endif %}..HEAD
    {% endif %}\
{% endfor %}
<!-- generated by git-cliff -->
"""

trim = true
render_always = true

[git]
conventional_commits = true
filter_unconventional = true
require_conventional = false
split_commits = false
protect_breaking_commits = false
filter_commits = false
topo_order = false
topo_order_commits = true
sort_commits = "oldest"
tag_pattern = "v[0-9]+\\.[0-9]+\\.[0-9]+"

commit_parsers = [
    { message = "^feat", group = "Agregado" },
    { message = "^refactor", group = "Cambiado" },
    { message = "^perf", group = "Cambiado" },
    { message = "^style", group = "Cambiado" },
    { message = "^fix", group = "Arreglado" },
    { body = ".*security", group = "Seguridad" },
    { message = "^security", group = "Seguridad" },
    { message = "^deprecat", group = "Obsoleto" },
    { message = "^remove|^revert", group = "Eliminado" },
    { message = "^chore\\(release\\)", skip = true },
    { message = "^chore\\(deps", skip = true },
    { message = "^chore\\(pr\\)", skip = true },
    { message = "^chore\\(pull\\)", skip = true },
    { message = "^Merge", skip = true },
    { message = "^wip", skip = true },
    { message = "^doc", group = "Misceláneos" },
    { message = "^test", group = "Misceláneos" },
    { message = "^chore|^ci|^build", group = "Misceláneos" },
]
